default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  # username: root
  # password: password
  # host: cmmteam4_backend-mysql-1
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: group3_development

test:
  <<: *default
  database: group3_test

production:
  <<: *default
  database: group3_production
  # adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000
  # username: slack_app
  # password: <%= ENV['SLACK_APP_DATABASE_PASSWORD'] %>
